//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skating
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dancers
    {
        public int DancerId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string City { get; set; }
        public int ClubId { get; set; }
        public int PairId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> GenderId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Clubs Clubs { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Pairs Pairs { get; set; }
    }
}
