//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruppy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruppy()
        {
            this.SudeyskiySostav = new HashSet<SudeyskiySostav>();
        }
    
        public int IdGruppy { get; set; }
        public int Nomer { get; set; }
        public int IdTipaVystupleniya { get; set; }
        public int KolichestvoTancev { get; set; }
        public string Nazvanie { get; set; }
    
        public virtual TipyVystupleniya TipyVystupleniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SudeyskiySostav> SudeyskiySostav { get; set; }
    }
}
