//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pary
    {
        public int IdPary { get; set; }
        public int IdUchastnika { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public int NomerPary { get; set; }
        public int IdKluba { get; set; }
    
        public virtual Kluby Kluby { get; set; }
        public virtual Uchastniki Uchastniki { get; set; }
    }
}
