//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultaty
    {
        public int IdPary { get; set; }
        public int IdTura { get; set; }
        public int IdTanca { get; set; }
        public int Mesto { get; set; }
        public string SrednyayaOcenka { get; set; }
        public int IdSorevnovaniya { get; set; }
    
        public virtual Pary Pary { get; set; }
        public virtual Tanceval_nyeNomera Tanceval_nyeNomera { get; set; }
        public virtual Tury Tury { get; set; }
    }
}
