//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatyTanca
    {
        public int IdTanca { get; set; }
        public int IdGruppy { get; set; }
        public string C1 { get; set; }
        public string C1_2 { get; set; }
        public string C1_3 { get; set; }
        public string C1_4 { get; set; }
        public string C1_5 { get; set; }
        public string C1_6 { get; set; }
        public string C1_7 { get; set; }
        public string C1_8 { get; set; }
        public string Mesto { get; set; }
    
        public virtual Gruppy Gruppy { get; set; }
        public virtual Tanceval_nyeNomera Tanceval_nyeNomera { get; set; }
    }
}
