//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorevnovaniya
    {
        public int IdSorevnovaniya { get; set; }
        public string DolyaPar { get; set; }
        public int KolichestvoSudej { get; set; }
        public int KolichestvoPar { get; set; }
        public int IdSpiskaUchastnikov { get; set; }
        public int IdSpiskaSudey { get; set; }
        public int IdProgrammy { get; set; }
        public string Gorod { get; set; }
        public Nullable<int> IdOrganizacii { get; set; }
    
        public virtual Organizacii Organizacii { get; set; }
        public virtual SpisokSudey SpisokSudey { get; set; }
        public virtual SpisokUchastnikov SpisokUchastnikov { get; set; }
        public virtual Tanceval_nayaProgramma Tanceval_nayaProgramma { get; set; }
    }
}
