//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorevnovaniya
    {
        public int IdSorevnovaniya { get; set; }
        public string Nazvanie { get; set; }
        public string Gorod { get; set; }
        public Nullable<int> IdKluba { get; set; }
    
        public virtual Kluby Kluby { get; set; }
    }
}
