//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokSudey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpisokSudey()
        {
            this.Sorevnovaniya = new HashSet<Sorevnovaniya>();
            this.SudeyskiySostav = new HashSet<SudeyskiySostav>();
        }
    
        public int IdSpiskaSudey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovaniya> Sorevnovaniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SudeyskiySostav> SudeyskiySostav { get; set; }
    }
}
