//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SudeyskiySostav
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SudeyskiySostav()
        {
            this.OcenkaTanca = new HashSet<OcenkaTanca>();
        }
    
        public int IdSud_i { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Gorod { get; set; }
        public int IdSpiskaSudey { get; set; }
        public int IdTipa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenkaTanca> OcenkaTanca { get; set; }
        public virtual SpisokSudey SpisokSudey { get; set; }
        public virtual TipySudeyskogoSostava TipySudeyskogoSostava { get; set; }
    }
}
