//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanceval_nyeNomera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tanceval_nyeNomera()
        {
            this.OcenkaTanca = new HashSet<OcenkaTanca>();
            this.ResultatyTanca = new HashSet<ResultatyTanca>();
            this.Tanceval_nayaProgramma = new HashSet<Tanceval_nayaProgramma>();
        }
    
        public int IdTanca { get; set; }
        public string NazvaniyeTanca { get; set; }
        public string KratkoeNazvaniye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenkaTanca> OcenkaTanca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatyTanca> ResultatyTanca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tanceval_nayaProgramma> Tanceval_nayaProgramma { get; set; }
    }
}
