//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchastniki
    {
        public int IdUchastnika { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public System.DateTime DataRozhdeniya { get; set; }
        public string Gorod { get; set; }
        public int IdKluba { get; set; }
        public int IdKategorii { get; set; }
        public int IdPary { get; set; }
    
        public virtual Kluby Kluby { get; set; }
        public virtual Pary Pary { get; set; }
        public virtual VozrastnyeKategorii VozrastnyeKategorii { get; set; }
    }
}
