//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skating
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanceScore
    {
        public int DanceId { get; set; }
        public int PairId { get; set; }
        public int JudgeId { get; set; }
        public int Place { get; set; }
    
        public virtual Dances Dances { get; set; }
        public virtual Judges Judges { get; set; }
        public virtual Pairs Pairs { get; set; }
    }
}
